package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/BadlyFormedMatchText.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class BadlyFormedMatchText extends java.lang.Exception
{
  public org.hl7.types.ST matchText = null;

  public BadlyFormedMatchText ()
  {
    // super(BadlyFormedMatchTextHelper.id());
  } // ctor

  public BadlyFormedMatchText (org.hl7.types.ST _matchText)
  {
    // super(BadlyFormedMatchTextHelper.id());
    matchText = _matchText;
  } // ctor


  public BadlyFormedMatchText (String $reason, org.hl7.types.ST _matchText)
  {
    // super(BadlyFormedMatchTextHelper.id() + "  " + $reason);
    matchText = _matchText;
  } // ctor

} // class BadlyFormedMatchText
