package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/BrowserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/


/** 
 *<PRE>HL7SpecBlock:browser </PRE>
 */
public interface BrowserOperations  extends org.hl7.CTSMAPI.IdentificationOperations
{

  /** 
 *<PRE>Return a list of supported match algorithms </PRE>
 */
  org.hl7.types.ST[] getSupportedMatchAlgorithms () throws org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Coded attributes known to the browser whose names meets the supplied criteria
   *
   *	matchText		- Match string.  Format depends upon the match algorithm. Empty string means return all names
   *	matchAlgorithm_code	- Match algorithm code. 
   *	timeout			- time limit for operation to complete in milliseconds (0 means unlimited
   *	sizeLimit		- maximum number of elements to return (0 means unlimited)
   *
   *	Returns			- list of coded attributes
   *
   *	NOTE: if a sizeLimit has been specified and the number of entries in the list is the same as the size limit,
   *	      the caller must presume that the list is incomplete.
   *
   *	Exceptions
   *		TimeoutError		- time limit was exceeded
   *		BadlyFormedMatchText  	- match text couldn't be parsed for the supplied algorithm
   *		UnknownMatchAlgorithm - match algorithm was unrecognized by service
   </PRE>
 */
  org.hl7.CTSMAPI.RIMCodedAttribute[] getSupportedAttributes (org.hl7.types.ST matchText, org.hl7.types.ST matchAlgorithm_code, int timeout, int sizeLimit) throws org.hl7.CTSMAPI.BadlyFormedMatchText, org.hl7.CTSMAPI.UnknownMatchAlgorithm, org.hl7.CTSMAPI.TimeoutError, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Vocabulary domains known to the browser whose names meet the supplied criteria
   *
   *	matchText		- Match string.  Format depends upon the match algorithm. Empty string means return all names
   *	matchAlgorithm_code	- Match algorithm code.
   *	timeout			- time limit for operation to complete in milliseconds (0 means unlimited
   *	sizeLimit		- maximum number of elements to return (0 means unlimited)
   *
   *	Returns			- list of vocabulary domains
   *
   *	NOTE: if a sizeLimit has been specified and the number of entries in the list is the same as the size limit,
   *	      the caller must presume that the list is incomplete.
   *
   *	Exceptions
   *		TimeoutError		- time limit was exceeded
   *		BadlyFormedMatchText  	- match text couldn't be parsed for the supplied algorithm
   *		UnknownMatchAlgorithm 	- match algorithm was unrecognized by service
   </PRE>
 */
  org.hl7.types.ST[] getSupportedVocabularyDomains (org.hl7.types.ST matchText, org.hl7.types.ST matchAlgorithm_code, int timeout, int sizeLimit) throws org.hl7.CTSMAPI.BadlyFormedMatchText, org.hl7.CTSMAPI.UnknownMatchAlgorithm, org.hl7.CTSMAPI.TimeoutError, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Value sets known to the browser having names matching the passed match text
   *
   *	matchText		- Match string.  Format depends upon the match algorithm. Empty string means return all names
   *	matchAlgorithm_code	- Match algorithm code.
   *	timeout			- time limit for operation to complete in milliseconds (0 means unlimited
   *	sizeLimit		- maximum number of elements to return (0 means unlimited)
   *
   *	Returns			- list of value sets
   *
   *	NOTE: if a sizeLimit has been specified and the number of entries in the list is the same as the size limit,
   *	      the caller must presume that the list is incomplete.
   *
   *	Exceptions
   *		TimeoutError		- time limit was exceeded
   *		BadlyFormedMatchText  	- match text couldn't be parsed for the supplied algorithm
   *		UnknownMatchAlgorithm 	- match algorithm was unrecognized by service
   </PRE>
 */
  org.hl7.CTSMAPI.ValueSetDescriptor[] getSupportedValueSets (org.hl7.types.ST matchText, org.hl7.types.ST matchAlgorithm_code, int timeout, int sizeLimit) throws org.hl7.CTSMAPI.BadlyFormedMatchText, org.hl7.CTSMAPI.UnknownMatchAlgorithm, org.hl7.CTSMAPI.TimeoutError, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Code Systems known to the browser whose name match the supplied criteria
   *
   *
   *	matchText		- Match string.  Format depends upon the match algorithm. Empty string means return all names
   *	matchAlgorithm_code	- Match algorithm code.
   *	timeout			- time limit for operation to complete in milliseconds (0 means unlimited
   *	sizeLimit		- maximum number of elements to return (0 means unlimited)
   *
   *	Returns			- list of code systems
   *
   *	NOTE: if a sizeLimit has been specified and the number of entries in the list is the same as the size limit,
   *	      the caller must presume that the list is incomplete.
   *
   *	Exceptions
   *		TimeoutError		- time limit was exceeded
   *		BadlyFormedMatchText  	- match text couldn't be parsed for the supplied algorithm
   *		UnknownMatchAlgorithm 	- match algorithm was unrecognized by service
   </PRE>
 */
  org.hl7.CTSMAPI.CodeSystemDescriptor[] getSupportedCodeSystems (org.hl7.types.ST matchText, org.hl7.types.ST matchAlgorithm_code, int timeout, int sizeLimit) throws org.hl7.CTSMAPI.BadlyFormedMatchText, org.hl7.CTSMAPI.UnknownMatchAlgorithm, org.hl7.CTSMAPI.TimeoutError, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Look up the full description of a vocabulary domain
   *	domain	- vocabulary domain identifier to look up
   *
   *	Returns - full description of the vocabulary domain
   </PRE>
 */
  org.hl7.CTSMAPI.VocabularyDomainDescription lookupVocabularyDomain (org.hl7.types.ST vocabularyDomain_name) throws org.hl7.CTSMAPI.UnknownVocabularyDomain, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Look up the full description of a value set
   * valueSet - unique identifier or name of a value set
   *
   * Returns - full description of the value set
   *
   * Exceptions
   *		UnknownValueSet		- if present, the value set id isn't recognized by the service or
   *					  if the id is absent, the name isn't recognized by the service
   *					  neither the name nor the id was supplied
   *		ValueSetNameIdMismatch 	- the value set code is valid in the service, but
   *					  the name doesn't match the code
   </PRE>
 */
  org.hl7.CTSMAPI.FullValueSetDescription lookupValueSet (org.hl7.types.ST valueSet_id, org.hl7.types.ST valueSet_name) throws org.hl7.CTSMAPI.UnknownValueSet, org.hl7.CTSMAPI.ValueSetNameIdMismatch, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Look up the description and name of a code system
   *	codeSystem - unique code system identifier
   *
   * Returns - description of the code system
   *
   * Exceptions
   *		UnknownCodeSystem 	- the code system id was supplied and isn't recognized by the service
   *					  only the code system name was supplied and it isn't recognized by the service
   *					  neither the code system id nor the name was supplied
   *		CodeSystemNameIdMismatch - both the code system id and name were supplied and the name
   *					   didn't match the id
   </PRE>
 */
  org.hl7.CTSMAPI.CodeSystemInfo lookupCodeSystem (org.hl7.types.UID codeSystem_id, org.hl7.types.ST codeSystem_name) throws org.hl7.CTSMAPI.UnknownCodeSystem, org.hl7.CTSMAPI.CodeSystemNameIdMismatch, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Return the descriptor of the value set that would be used for the vocabulary domain in the given context (if any)
   *
   *      vocabularyDomain_name       - name of the vocabulary domain vocabulary domain
   *	applicationContext_code	    - applicable context (optional)
   *
   *      Returns         - The identifier and name(if any) of the value set that would be used in this context
   *
   *	Exceptions
   *			UnknownVocabularyDomain - the vocabulary domain isn't recognized by the service
   *			UnknownApplicationContextCode	- the application context isn't recognized by the service
   *			NoApplicableValueSet	- there isn't a value set that applies to this domain in this context
   *
   </PRE>
 */
  org.hl7.CTSMAPI.ValueSetDescriptor lookupValueSetForDomain (org.hl7.types.ST vocabularyDomain_name, org.hl7.types.ST applicationContext_code) throws org.hl7.CTSMAPI.UnknownVocabularyDomain, org.hl7.CTSMAPI.UnknownApplicationContextCode, org.hl7.CTSMAPI.NoApplicableValueSet, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Determine whether a given concept code is in a value set
   *	valueSet_id	- Value set identifier	(optional but at least one of id or name must be supplied)
   *	valueSet_name	- Name of the value set (optional 	             "
   *     	includeHeadCode - True means that the "headcode" of the value set, if any,
   *			  should be considered part of the set
   *     	codeToValidate  - code system and concept code to validate
   *
   *    	Returns         - TRUE if the concept belongs to the code set
   *                        FALSE otherwise.
   *
   *	Exceptions
   *
   *		UnknownValueSet		- if present, the value set id isn't recognized by the service or
   *					  if the id is absent, the name isn't recognized by the service
   *		ValueSetNameIdMismatch 	- the value set code is valid in the service, but
   *					  the name doesn't match the code
   *		UnknownCodeSystem	- the code system isn't recognized by the service
   *		UnknownConceptCode 	- the concept code isn't valid in the code system
   *
   </PRE>
 */
  org.hl7.types.BL isCodeInValueSet (org.hl7.types.ST valueSet_id, org.hl7.types.ST valueSet_name, org.hl7.types.BL includeHeadCode, org.hl7.CTSMAPI.ConceptId codeToValidate) throws org.hl7.CTSMAPI.UnknownValueSet, org.hl7.CTSMAPI.ValueSetNameIdMismatch, org.hl7.CTSMAPI.UnknownConceptCode, org.hl7.CTSMAPI.UnknownCodeSystem, org.hl7.CTSMAPI.UnexpectedError;
} // interface BrowserOperations
