package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/CodeSystemInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/**

 *<PRE> * Complete information about a code system
 *	description	- name, identifier and supported versions of the code system
 *	registrationInfo - additional registration information as recorded by HL7
 </PRE>
 */
public final class CodeSystemInfo implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.CTSMAPI.CodeSystemDescriptor description = null;
  public org.hl7.CTSMAPI.CodeSystemRegistration registrationInfo = null;

  public CodeSystemInfo ()
  {
  } // ctor

  public CodeSystemInfo (org.hl7.CTSMAPI.CodeSystemDescriptor _description, org.hl7.CTSMAPI.CodeSystemRegistration _registrationInfo)
  {
    description = _description;
    registrationInfo = _registrationInfo;
  } // ctor

} // class CodeSystemInfo
