package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/CodeSystemNameIdMismatch.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class CodeSystemNameIdMismatch extends java.lang.Exception
{
  public org.hl7.types.UID codeSystem_id = null;
  public org.hl7.types.ST codeSystem_name = null;

  public CodeSystemNameIdMismatch ()
  {
    // super(CodeSystemNameIdMismatchHelper.id());
  } // ctor

  public CodeSystemNameIdMismatch (org.hl7.types.UID _codeSystem_id, org.hl7.types.ST _codeSystem_name)
  {
    // super(CodeSystemNameIdMismatchHelper.id());
    codeSystem_id = _codeSystem_id;
    codeSystem_name = _codeSystem_name;
  } // ctor


  public CodeSystemNameIdMismatch (String $reason, org.hl7.types.UID _codeSystem_id, org.hl7.types.ST _codeSystem_name)
  {
    // super(CodeSystemNameIdMismatchHelper.id() + "  " + $reason);
    codeSystem_id = _codeSystem_id;
    codeSystem_name = _codeSystem_name;
  } // ctor

} // class CodeSystemNameIdMismatch
