package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/CodeSystemDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/** 
 *<PRE>Code System Descriptor                                                   
 *	codeSystem_id		- OID of code system                        
 *	codeSystem_name		- mnemonic code system name
 *	copyright		- copyright notice for the code system               
 *	availableReleases 	- the release of the represented code system
 </PRE>
 */
public final class CodeSystemDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.types.UID codeSystem_id = null;
  public org.hl7.types.ST codeSystem_name = null;
  public org.hl7.types.ST copyright = null;
  public org.hl7.types.ST availableReleases[] = null;

  public CodeSystemDescriptor ()
  {
  } // ctor

  public CodeSystemDescriptor (org.hl7.types.UID _codeSystem_id, org.hl7.types.ST _codeSystem_name, org.hl7.types.ST _copyright, org.hl7.types.ST[] _availableReleases)
  {
    codeSystem_id = _codeSystem_id;
    codeSystem_name = _codeSystem_name;
    copyright = _copyright;
    availableReleases = _availableReleases;
  } // ctor

} // class CodeSystemDescriptor
