package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/CTSVersionId.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/** 
 *<PRE>CTS Specification Version Identifier </PRE>
 */
public final class CTSVersionId implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.types.INT major = null;
  public org.hl7.types.INT minor = null;

  public CTSVersionId ()
  {
  } // ctor

  public CTSVersionId (org.hl7.types.INT _major, org.hl7.types.INT _minor)
  {
    major = _major;
    minor = _minor;
  } // ctor

} // class CTSVersionId
