package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/FullValueSetDescription.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/** 
 *<PRE>Value Set - a complete description of a value set used for browsing
 *	description	- a description of the value set
 *	constructedUsing - value sets used to define this set
 *	usedToDefine	- value sets that this set is used in the definition of
 *	referencesCodes - specific codes that are include ro excluded from this set
 </PRE>
 */
public final class FullValueSetDescription implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.CTSMAPI.ValueSetDescription description = null;
  public org.hl7.CTSMAPI.ValueSetConstructor constructedUsingValueSets[] = null;
  public org.hl7.CTSMAPI.ValueSetDescriptor usedToDefine[] = null;
  public org.hl7.CTSMAPI.ValueSetCodeReference referencesCodes[] = null;

  public FullValueSetDescription ()
  {
  } // ctor

  public FullValueSetDescription (org.hl7.CTSMAPI.ValueSetDescription _description, org.hl7.CTSMAPI.ValueSetConstructor[] _constructedUsingValueSets, org.hl7.CTSMAPI.ValueSetDescriptor[] _usedToDefine, org.hl7.CTSMAPI.ValueSetCodeReference[] _referencesCodes)
  {
    description = _description;
    constructedUsingValueSets = _constructedUsingValueSets;
    usedToDefine = _usedToDefine;
    referencesCodes = _referencesCodes;
  } // ctor

} // class FullValueSetDescription
