package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/IdentificationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/


/** 
 *<PRE>HL7SpecBlock:identification </PRE>
 */
public interface IdentificationOperations 
{
  org.hl7.types.ST getServiceName () throws org.hl7.CTSMAPI.UnexpectedError;
  org.hl7.types.ST getServiceVersion () throws org.hl7.CTSMAPI.UnexpectedError;
  org.hl7.types.ST getServiceDescription () throws org.hl7.CTSMAPI.UnexpectedError;
  org.hl7.types.ST getHL7ReleaseVersion () throws org.hl7.CTSMAPI.UnexpectedError;
  org.hl7.CTSMAPI.CTSVersionId getCTSVersion () throws org.hl7.CTSMAPI.UnexpectedError;
} // interface IdentificationOperations
