package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/InvalidExpansionContext.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class InvalidExpansionContext extends java.lang.Exception
{

  public InvalidExpansionContext ()
  {
    // super(InvalidExpansionContextHelper.id());
  } // ctor


  public InvalidExpansionContext (String $reason)
  {
    // super(InvalidExpansionContextHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidExpansionContext
