package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/NoApplicableValueSet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class NoApplicableValueSet extends java.lang.Exception
{
  public org.hl7.types.ST vocabularyDomain_name = null;
  public org.hl7.types.ST applicationContext_code = null;

  public NoApplicableValueSet ()
  {
    // super(NoApplicableValueSetHelper.id());
  } // ctor

  public NoApplicableValueSet (org.hl7.types.ST _vocabularyDomain_name, org.hl7.types.ST _applicationContext_code)
  {
    // super(NoApplicableValueSetHelper.id());
    vocabularyDomain_name = _vocabularyDomain_name;
    applicationContext_code = _applicationContext_code;
  } // ctor


  public NoApplicableValueSet (String $reason, org.hl7.types.ST _vocabularyDomain_name, org.hl7.types.ST _applicationContext_code)
  {
    // super(NoApplicableValueSetHelper.id() + "  " + $reason);
    vocabularyDomain_name = _vocabularyDomain_name;
    applicationContext_code = _applicationContext_code;
  } // ctor

} // class NoApplicableValueSet
