package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/NoApplicableDesignationFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class NoApplicableDesignationFound extends java.lang.Exception
{
  public org.hl7.types.CD codeToFillIn = null;
  public org.hl7.types.ST displayLanguage_code = null;

  public NoApplicableDesignationFound ()
  {
    // super(NoApplicableDesignationFoundHelper.id());
  } // ctor

  public NoApplicableDesignationFound (org.hl7.types.CD _codeToFillIn, org.hl7.types.ST _displayLanguage_code)
  {
    // super(NoApplicableDesignationFoundHelper.id());
    codeToFillIn = _codeToFillIn;
    displayLanguage_code = _displayLanguage_code;
  } // ctor


  public NoApplicableDesignationFound (String $reason, org.hl7.types.CD _codeToFillIn, org.hl7.types.ST _displayLanguage_code)
  {
    // super(NoApplicableDesignationFoundHelper.id() + "  " + $reason);
    codeToFillIn = _codeToFillIn;
    displayLanguage_code = _displayLanguage_code;
  } // ctor

} // class NoApplicableDesignationFound
