package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/QualifiersNotSupported.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class QualifiersNotSupported extends java.lang.Exception
{

  public QualifiersNotSupported ()
  {
    // super(QualifiersNotSupportedHelper.id());
  } // ctor


  public QualifiersNotSupported (String $reason)
  {
    // super(QualifiersNotSupportedHelper.id() + "  " + $reason);
  } // ctor

} // class QualifiersNotSupported
