package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/RIMAttributeId.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/** 
 *<PRE>RIM Coded Attribute identifier.  All three elements are necessary to make the id unique
 *      model_id    	- RIM model identifier
 *      class_name 	- class name
 *      attribute_name 	- name of the attribute within the model
 </PRE>
 */
public final class RIMAttributeId implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.types.ST model_id = null;
  public org.hl7.types.ST class_name = null;
  public org.hl7.types.ST attribute_name = null;

  public RIMAttributeId ()
  {
  } // ctor

  public RIMAttributeId (org.hl7.types.ST _model_id, org.hl7.types.ST _class_name, org.hl7.types.ST _attribute_name)
  {
    model_id = _model_id;
    class_name = _class_name;
    attribute_name = _attribute_name;
  } // ctor

} // class RIMAttributeId
