package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/RuntimeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/


/** 
 *<PRE>HL7SpecBlock:runtime </PRE>
 */
public interface RuntimeOperations  extends org.hl7.CTSMAPI.IdentificationOperations
{

  /** 
 *<PRE>Return a list of supported match algorithms </PRE>
 */
  org.hl7.types.ST[] getSupportedMatchAlgorithms () throws org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Vocabulary domains known to the runtime module 
   *
   *	matchText		- Match string.  Format depends upon the match algorithm. Empty string means return all names
   *	matchAlgorithm_code	- Match algorithm code.
   *	timeout			- time limit for operation to complete in milliseconds (0 means unlimited
   *	sizeLimit		- maximum number of elements to return (0 means unlimited)
   *
   *	Returns			- list of vocabulary domains
   *
   *	NOTE: if a sizeLimit has been specified and the number of entries in the list is the same as the size limit,
   *	      the caller must presume that the list is incomplete.
   *
   *	Exceptions
   *		TimeoutError		- time limit was exceeded
   *		BadlyFormedMatchText  	- match text couldn't be parsed for the supplied algorithm
   *		UnknownMatchAlgorithm 	- match algorithm was unrecognized by service
   </PRE>
 */
  org.hl7.types.ST[] getSupportedVocabularyDomains (org.hl7.types.ST matchText, org.hl7.types.ST matchAlgorithm_code, int timeout, int sizeLimit) throws org.hl7.CTSMAPI.BadlyFormedMatchText, org.hl7.CTSMAPI.UnknownMatchAlgorithm, org.hl7.CTSMAPI.TimeoutError, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE> Validate a CD data element for a specified vocabulary domain
   *
   *      vocabularyDomain_name   - Vocabulary domain of the attribute
   *      codeToValidate          - code to be validated
   *      applicationContext_code	- application context (Optional)
   *      activeConceptsOnly     	- True means that code must be active within target
   *                        	  code system.  False means that inactive codes
   *                                are valid as well.  (Note that warnings will still be
   *                                generated for inactive codes).
   *      errorCheckOnly 		- True means limited validation (check for errors only)
   *                        	  False means extended validation (check for warnings and errors)
   *
   *      Returns         	- Structure containing count of errors (nErrors), count of warnings (nWarnings) followed by
   *			  	  detailed information
   *
   * NOTE:   This method validates the current code and qualifiers.  Use validateTranslations to
   *	   validate the code translations.
   *
   *	Exceptions
   *		UnknownVocabularyDomain	- the vocabulary domain isn't recognized by the service
   *		UnknownApplicationContextCode	- applicationContext isn't recognized
   *		NoApplicableValueSet	- there isn't a value set that applies to this domain in this context
   *
   </PRE>
 */
  org.hl7.CTSMAPI.ValidateCodeReturn validateCode (org.hl7.types.ST vocabularyDomain_name, org.hl7.types.CD codeToValidate, org.hl7.types.ST applicationContext_code, org.hl7.types.BL activeConceptsOnly, org.hl7.types.BL errorCheckOnly) throws org.hl7.CTSMAPI.UnknownVocabularyDomain, org.hl7.CTSMAPI.UnexpectedError, org.hl7.CTSMAPI.UnknownApplicationContextCode, org.hl7.CTSMAPI.NoApplicableValueSet;

  /** 
 *<PRE>Validate the set of CD translations
   *	vocabularyDomain_name   - Vocabulary domain of the attribute
   *      codeToValidate          - code to be validated
   *      applicationContext_code	- application context (Optional)
   *      activeConceptsOnly     	- True means that code must be active within target
   *                        	  code system.  False means that inactive codes
   *                                are valid as well.  (Note that warnings will still be
   *                                generated for inactive codes).
   *      errorCheckOnly 		- True means limited validation (check for errors only)
   *                        	  False means extended validation (check for warnings and errors)
   *
   *      Returns         	- Structure containing count of errors (nErrors), count of warnings (nWarnings) followed by
   *			  	  detailed information
   *
   * 	Exceptions
   *		UnknownVocabularyDomain - vocabulary domain isn't recognized by the service
   *		UnknownApplicationContextCode 	- application context isn't recognized by the service
   </PRE>
 */
  org.hl7.CTSMAPI.ValidateCodeReturn validateTranslation (org.hl7.types.ST vocabularyDomain_name, org.hl7.types.CD codeToValidate, org.hl7.types.ST applicationContext_code, org.hl7.types.BL activeConceptsOnly, org.hl7.types.BL errorCheckOnly) throws org.hl7.CTSMAPI.UnknownVocabularyDomain, org.hl7.CTSMAPI.UnknownApplicationContextCode, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Translate a coded attribute.  If a target code system is supplied, the supplied code
   *	is translated into the target code system.  If the target code system is omitted,
   *	the code is translated into a form that applies in the target context.
   *
   *      vocabularyDomain_name 	- vocabulary domain of code and translation
   *      fromCode        	- code to be translated
   *	tiCodeSystemId		- id of target code system (Optional)
   *      toApplicationContext_code - context that identifies the target setting
   *
   *	Returns			- New CD data element that includes the translation
   *
   *	Exceptions
   *		UnknownVocabularyDomain - the vocabulary domain isn't recognized by the service
   *		UnknownCodeSystem	- the code system in fromCode or the toCodeSystemId isn't
   *					recognized by the service
   *		UnknownApplicationContextCode	- the application context code isn't recognized by the service
   *		UnableToTranslate	- the translation failed for the reason specified
   *
   </PRE>
 */
  org.hl7.types.CD translateCode (org.hl7.types.ST vocabularyDomain_name, org.hl7.types.CD fromCode, org.hl7.types.UID toCodeSystemId, org.hl7.types.ST toApplicationContext_code) throws org.hl7.CTSMAPI.UnknownVocabularyDomain, org.hl7.CTSMAPI.UnknownCodeSystem, org.hl7.CTSMAPI.UnknownApplicationContextCode, org.hl7.CTSMAPI.UnableToTranslate, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Fill in the optional fields in a CD, including the code system name, release and the code display name.
   *      codeToFillIn		- code to be filled in
   *      displayLanguage_code 	- Language to be used for code system name and code designation
   *
   *	Returns		- filled in code
   *
   * Exceptions
   *	UnknownCodeSystem	- the code system part of code isn't recognized by the service
   *	UnknownConceptCode	- the concept code isn't valid in the supplied code system, or the code isn't valid
   *	UnknownLanguage		- the language code isn't recognized.
   *  NoApplicableDesignationFound - No designation exists for the supplied CD and language.
   *
   </PRE>
 */
  org.hl7.types.CD fillInDetails (org.hl7.types.CD codeToFillIn, org.hl7.types.ST displayLanguage_code) throws org.hl7.CTSMAPI.UnknownCodeSystem, org.hl7.CTSMAPI.UnknownConceptCode, org.hl7.CTSMAPI.UnknownLanguage, org.hl7.CTSMAPI.UnexpectedError, org.hl7.CTSMAPI.NoApplicableDesignationFound;

  /** 
 *<PRE>Determine whether the first code subsumes (implies) the second.
   *      parentCode      - the supertype code
   *      childCode       - the subtype code
   *
   *      Returns         - true if the parent subsumes the child
   *                      - false if the parent does not
   *
   *	NOTES:
   *		1) Translations are ignored in this call
   *		2) If the two codes are equivalent, the function will return true
   *		3) If one or both of the codes are exceptions (CWE) and the codes are
   *		   not equivalent, then the function returns false
   *
   *	Exceptions
   *		UnknownCodeSystem	- Either the parent or child code system aren't recognized
   *		UnknownConceptCode	- either parentCode or childCode isn't recognized by the service    
   *		SubsumptionNotSupported	- subsumption testing isn't supported by the service or code system
   *		UnrecognizedQualifier	- one of the concept qualifiers wasn't recognized by the service
   *		QualifiersNotSupported	- if qualified concepts aren't supported by this service
   </PRE>
 */
  org.hl7.types.BL subsumes (org.hl7.types.CD parentCode, org.hl7.types.CD childCode) throws org.hl7.CTSMAPI.UnknownCodeSystem, org.hl7.CTSMAPI.UnknownConceptCode, org.hl7.CTSMAPI.SubsumptionNotSupported, org.hl7.CTSMAPI.UnrecognizedQualifier, org.hl7.CTSMAPI.QualifiersNotSupported, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Determine whether the two codes should be considered equivalent
   *	code1		- the first code
   *	code2		- the second code
   *
   *	Returns		- true if the codes are determined to be equivalent, false otherwise
   *
   *	Exceptions
   *		UnknownCodeSystem	- Either the parent or child code system aren't recognized
   *		UnknownConceptCode	- either parentCode or childCode isn't recognized by the service    
   *		SubsumptionNotSupported	- subsumption testing isn't supported by the service or code system
   *		UnrecognizedQualifier	- one of the concept qualifiers wasn't recognized by the service
   *		QualifiersNotSupported	- if qualified concepts aren't supported by this service
   </PRE>
 */
  org.hl7.types.BL areEquivalent (org.hl7.types.CD code1, org.hl7.types.CD code2) throws org.hl7.CTSMAPI.UnknownCodeSystem, org.hl7.CTSMAPI.UnknownConceptCode, org.hl7.CTSMAPI.SubsumptionNotSupported, org.hl7.CTSMAPI.UnrecognizedQualifier, org.hl7.CTSMAPI.QualifiersNotSupported, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Return a hierarchical list of the valid values for the supplied vocabulary domain and context
   *      vocabularyDomain_name   - vocabulary domain to list
   *      applicationContext_code	- context used to select value set (optional)
   *      language_code	        - language to be used in the list display
   *      expandAll       	- true means return a complete list, false means one level
   *	timeout			- time limit for operation to complete in milliseconds (0 means unlimited
   *	sizeLimit		- maximum number of elements to return (0 means unlimited)
   *
   *      Returns         - list of valid codes
   *
   *	NOTE: if a sizeLimit has been specified and the number of entries in the list is the same as the size limit,
   *	      the caller must presume that the list is incomplete.
   *
   *	Exceptions
   *		UnknownVocabularyDomain		- domain not recognized by service
   *		UnknownApplicationContextCode	- application context not recognized by the service
   *		UnknownLanguage			- language code not recognized by the service
   *		NoApplicableValueSet	- there isn't a value set that applies to this domain in this context
   *		TimeoutError			- time limit was exceeded
   </PRE>
 */
  org.hl7.CTSMAPI.ValueSetExpansion[] lookupValueSetExpansion (org.hl7.types.ST vocabularyDomain_name, org.hl7.types.ST applicationContext_code, org.hl7.types.ST language_code, org.hl7.types.BL expandAll, int timeout, int sizeLimit) throws org.hl7.CTSMAPI.UnknownVocabularyDomain, org.hl7.CTSMAPI.UnknownApplicationContextCode, org.hl7.CTSMAPI.UnknownLanguage, org.hl7.CTSMAPI.NoApplicableValueSet, org.hl7.CTSMAPI.TimeoutError, org.hl7.CTSMAPI.UnexpectedError;

  /** 
 *<PRE>Expand an unexpanded node returned by lookupValueSetExpansion above
   *	expandContext		- starting context to expand
   *	Returns			- list of valid codes underneath context
   *
   </PRE>
 */
  org.hl7.CTSMAPI.ValueSetExpansion[] expandValueSetExpansionContext (byte[] expansionContext) throws org.hl7.CTSMAPI.InvalidExpansionContext, org.hl7.CTSMAPI.TimeoutError, org.hl7.CTSMAPI.UnexpectedError;
} // interface RuntimeOperations
