package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/TimeoutError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class TimeoutError extends java.lang.Exception
{

  public TimeoutError ()
  {
    // super(TimeoutErrorHelper.id());
  } // ctor


  public TimeoutError (String $reason)
  {
    // super(TimeoutErrorHelper.id() + "  " + $reason);
  } // ctor

} // class TimeoutError
