package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/UnableToTranslate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class UnableToTranslate extends java.lang.Exception
{

  public UnableToTranslate ()
  {
    // super(UnableToTranslateHelper.id());
  } // ctor


  public UnableToTranslate (String $reason)
  {
    // super(UnableToTranslateHelper.id() + "  " + $reason);
  } // ctor

} // class UnableToTranslate
