package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/UnexpectedError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class UnexpectedError extends java.lang.Exception
{
  public org.hl7.types.ST possible_cause = null;

  public UnexpectedError ()
  {
    // super(UnexpectedErrorHelper.id());
  } // ctor

  public UnexpectedError (org.hl7.types.ST _possible_cause)
  {
    // super(UnexpectedErrorHelper.id());
    possible_cause = _possible_cause;
  } // ctor


  public UnexpectedError (String $reason, org.hl7.types.ST _possible_cause)
  {
    // super(UnexpectedErrorHelper.id() + "  " + $reason);
    possible_cause = _possible_cause;
  } // ctor

} // class UnexpectedError
