package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/UnknownVocabularyDomain.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class UnknownVocabularyDomain extends java.lang.Exception
{
  public org.hl7.types.ST vocabularyDomain_name = null;

  public UnknownVocabularyDomain ()
  {
    // super(UnknownVocabularyDomainHelper.id());
  } // ctor

  public UnknownVocabularyDomain (org.hl7.types.ST _vocabularyDomain_name)
  {
    // super(UnknownVocabularyDomainHelper.id());
    vocabularyDomain_name = _vocabularyDomain_name;
  } // ctor


  public UnknownVocabularyDomain (String $reason, org.hl7.types.ST _vocabularyDomain_name)
  {
    // super(UnknownVocabularyDomainHelper.id() + "  " + $reason);
    vocabularyDomain_name = _vocabularyDomain_name;
  } // ctor

} // class UnknownVocabularyDomain
