package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/UnknownConceptCode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class UnknownConceptCode extends java.lang.Exception
{
  public org.hl7.CTSMAPI.ConceptId concept_id = null;

  public UnknownConceptCode ()
  {
    // super(UnknownConceptCodeHelper.id());
  } // ctor

  public UnknownConceptCode (org.hl7.CTSMAPI.ConceptId _concept_id)
  {
    // super(UnknownConceptCodeHelper.id());
      super(_concept_id.codeSystem_id.toString() +"#"+_concept_id.concept_code.toString());
    concept_id = _concept_id;
  } // ctor


  public UnknownConceptCode (String $reason, org.hl7.CTSMAPI.ConceptId _concept_id)
  {
    // super(UnknownConceptCodeHelper.id() + "  " + $reason);
    concept_id = _concept_id;
  } // ctor

} // class UnknownConceptCode
