package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/UnknownApplicationContextCode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class UnknownApplicationContextCode extends java.lang.Exception
{
  public org.hl7.types.ST applicationContext_code = null;

  public UnknownApplicationContextCode ()
  {
    // super(UnknownApplicationContextCodeHelper.id());
  } // ctor

  public UnknownApplicationContextCode (org.hl7.types.ST _applicationContext_code)
  {
    // super(UnknownApplicationContextCodeHelper.id());
    applicationContext_code = _applicationContext_code;
  } // ctor


  public UnknownApplicationContextCode (String $reason, org.hl7.types.ST _applicationContext_code)
  {
    // super(UnknownApplicationContextCodeHelper.id() + "  " + $reason);
    applicationContext_code = _applicationContext_code;
  } // ctor

} // class UnknownApplicationContextCode
