package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/UnrecognizedQualifier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class UnrecognizedQualifier extends java.lang.Exception
{
  public org.hl7.types.CR qualifier = null;

  public UnrecognizedQualifier ()
  {
    // super(UnrecognizedQualifierHelper.id());
  } // ctor

  public UnrecognizedQualifier (org.hl7.types.CR _qualifier)
  {
    // super(UnrecognizedQualifierHelper.id());
    qualifier = _qualifier;
  } // ctor


  public UnrecognizedQualifier (String $reason, org.hl7.types.CR _qualifier)
  {
    // super(UnrecognizedQualifierHelper.id() + "  " + $reason);
    qualifier = _qualifier;
  } // ctor

} // class UnrecognizedQualifier
