package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/ValidateCodeReturn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/


/** 
 *<PRE>Validate code return structure
 *	nErrors		- number of errors encountered
 *	nWarnings	- number of warnings encountered
 *	detail		- error and warning detail
 </PRE>
 */
public final class ValidateCodeReturn implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.types.INT nErrors = null;
  public org.hl7.types.INT nWarnings = null;
  public org.hl7.CTSMAPI.ValidationDetail detail[] = null;

  public ValidateCodeReturn ()
  {
  } // ctor

  public ValidateCodeReturn (org.hl7.types.INT _nErrors, org.hl7.types.INT _nWarnings, org.hl7.CTSMAPI.ValidationDetail[] _detail)
  {
    nErrors = _nErrors;
    nWarnings = _nWarnings;
    detail = _detail;
  } // ctor

} // class ValidateCodeReturn
