package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/ValidationDetail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/


/** 
 *<PRE>Code validation error detail
 *	codeInError	- the part of the coded attribute that is in error (base code, translation,
 *			  qualifier name or qualifier value)
 *      isError         - true means that this error is considered significant enough that a
 *                        message that contains it would not be valid
 *                        false means that the error is non-fatal but represents a potential
 *                        flaw somewhere in the formation process
 *      error_id        - a unique error identifer. 
 *      errorText       - text associated with the error identifier.
 </PRE>
 */
public final class ValidationDetail implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.types.CD codeInError = null;
  public org.hl7.types.BL isError = null;
  public org.hl7.types.ST error_id = null;
  public org.hl7.types.ST errorText = null;

  public ValidationDetail ()
  {
  } // ctor

  public ValidationDetail (org.hl7.types.CD _codeInError, org.hl7.types.BL _isError, org.hl7.types.ST _error_id, org.hl7.types.ST _errorText)
  {
    codeInError = _codeInError;
    isError = _isError;
    error_id = _error_id;
    errorText = _errorText;
  } // ctor

} // class ValidationDetail
