package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/ValueSetNameIdMismatch.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:10 AM EDT
*/

public final class ValueSetNameIdMismatch extends java.lang.Exception
{
  public org.hl7.types.ST valueSet_id = null;
  public org.hl7.types.ST valueSet_name = null;

  public ValueSetNameIdMismatch ()
  {
    // super(ValueSetNameIdMismatchHelper.id());
  } // ctor

  public ValueSetNameIdMismatch (org.hl7.types.ST _valueSet_id, org.hl7.types.ST _valueSet_name)
  {
    // super(ValueSetNameIdMismatchHelper.id());
    valueSet_id = _valueSet_id;
    valueSet_name = _valueSet_name;
  } // ctor


  public ValueSetNameIdMismatch (String $reason, org.hl7.types.ST _valueSet_id, org.hl7.types.ST _valueSet_name)
  {
    // super(ValueSetNameIdMismatchHelper.id() + "  " + $reason);
    valueSet_id = _valueSet_id;
    valueSet_name = _valueSet_name;
  } // ctor

} // class ValueSetNameIdMismatch
