package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/ValueSetConstructor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/** 
 *<PRE>Value Set Constructor - a value set that is used as part of another value set
 *	includeHeadCode	- True means that the included ValueSet head_code is considered part of the constructed set
 *			  False means it is not
 *	includedValueSet - value set used to define the constructed set
 </PRE>
 */
public final class ValueSetConstructor implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.CTSMAPI.ValueSetDescriptor includedValueSet = null;
  public org.hl7.types.BL includeHeadCode = null;

  public ValueSetConstructor ()
  {
  } // ctor

  public ValueSetConstructor (org.hl7.CTSMAPI.ValueSetDescriptor _includedValueSet, org.hl7.types.BL _includeHeadCode)
  {
    includedValueSet = _includedValueSet;
    includeHeadCode = _includeHeadCode;
  } // ctor

} // class ValueSetConstructor
