package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/ValueSetDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/** 
 *<PRE>Value Set Descriptor - a value set can be uniquely identified by either the value set
 *	id or the value set name.  Not all value sets, however, will have a name component.
 *	valueSet_id	- the unique value set identifier
 *	valueSet_name	- the unique value set name (not present for all value sets)
 </PRE>
 */
public final class ValueSetDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.types.ST valueSet_id = null;
  public org.hl7.types.ST valueSet_name = null;

  public ValueSetDescriptor ()
  {
  } // ctor

  public ValueSetDescriptor (org.hl7.types.ST _valueSet_id, org.hl7.types.ST _valueSet_name)
  {
    valueSet_id = _valueSet_id;
    valueSet_name = _valueSet_name;
  } // ctor

} // class ValueSetDescriptor
