package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/ValueSetCodeReference.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/** 
 *<PRE>Code Reference - a value set reference to a concept code
 *	referenced_code 	- a code from the containing value set's code system
 *	includeReferencedCode 	- True means that the referenced code is a part of the code set.  False means that
 *				  only the related concept codes are
 *	leafOnly		- True means that only the leaf nodes of the related concepts are included. False means that
 *				  intermediate nodes are included as well 
 *	relationship	- a code that identifies the relationship to be used.  If present, all concepts that are
 *			 children of the referencedCode are included (subject to includeReferencedCode and leafOnly restrictions)
 </PRE>
 */
public final class ValueSetCodeReference implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.types.ST referenced_code = null;
  public org.hl7.types.ST relationship_code = null;
  public org.hl7.types.BL includeReferencedCode = null;
  public org.hl7.types.BL leafOnly = null;

  public ValueSetCodeReference ()
  {
  } // ctor

  public ValueSetCodeReference (org.hl7.types.ST _referenced_code, org.hl7.types.ST _relationship_code, org.hl7.types.BL _includeReferencedCode, org.hl7.types.BL _leafOnly)
  {
    referenced_code = _referenced_code;
    relationship_code = _relationship_code;
    includeReferencedCode = _includeReferencedCode;
    leafOnly = _leafOnly;
  } // ctor

} // class ValueSetCodeReference
