package org.hl7.CTSMAPI;


/**
* org/hl7/CTSMAPI/VocabularyDomainValueSet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from idl/CTSMAPI.idl
* Monday, April 21, 2003 10:17:09 AM EDT
*/


/** 
 *<PRE>Vocabulary Domain Value Set - the association of a vocabulary domain with a value set in an optional context
 *	definedByValueSet - value set id and optional name that defines the vocabulary domain
 *	appliesIncontext  - the context in which the value set applies
 </PRE>
 */
public final class VocabularyDomainValueSet implements org.omg.CORBA.portable.IDLEntity
{
  public org.hl7.CTSMAPI.ValueSetDescriptor definedByValueSet = null;
  public org.hl7.types.ST applicationContext_code = null;

  public VocabularyDomainValueSet ()
  {
  } // ctor

  public VocabularyDomainValueSet (org.hl7.CTSMAPI.ValueSetDescriptor _definedByValueSet, org.hl7.types.ST _applicationContext_code)
  {
    definedByValueSet = _definedByValueSet;
    applicationContext_code = _applicationContext_code;
  } // ctor

} // class VocabularyDomainValueSet
