#! /bin/sh

# $Id: sourceGen,v 1.1 2006-10-03 19:42:17 marwahah Exp $

if [ -z "$JAVA_HOME" ] ; then
  JAVA=`which java`
  if [ -z "$JAVA" ] ; then
    echo "Cannot find JAVA. Please set your PATH."
    exit 1
  fi
  JAVA_BIN=`dirname $JAVA`
  JAVA_HOME=$JAVA_BIN/..
fi

JAVA=$JAVA_HOME/bin/java

CLASSPATH=`echo *.jar | tr ' ' ':'`:$CLASSPATH:.

$JAVA -cp $CLASSPATH org.exolab.castor.builder.SourceGenerator $@

