--
-- CRM DDL
--

-- basic table definitions
CREATE TABLE SBREXT.FORM_COLLECTIONS (
  FORM_COLLECTION_IDSEQ CHAR(36) PRIMARY KEY,
  DESCRIPTION VARCHAR2(2000),
  NAME VARCHAR2(255) NOT NULL,
  XML_FILE_NAME VARCHAR2(255),
  XML_FILE_PATH VARCHAR2(255),
  DATE_CREATED DATE,
  CREATED_BY VARCHAR2(30)
);


CREATE TABLE SBREXT.FORMS_IN_COLLECTION (
  FORM_COLLECTION_IDSEQ CHAR(36) NOT NULL,
  FORM_IDSEQ CHAR(36) NOT NULL,
  PUBLIC_ID NUMBER NOT NULL, 
  VERSION NUMBER(4,2) NOT NULL
);

rem alter table SBREXT.FORMS_IN_COLLECTION add foreign key (FORM_COLLECTION_IDSEQ) references SBREXT .FORM_COLLECTIONS(COLLECTION_IDSEQ);

rem DROP TABLE FORM_COLLECTIONS
rem DROP TABLE FORMS_IN_COLLECTION
