-- Request new login user "FORMLOADER"


--
-- CRM DDL
--

-- basic table definitions
CREATE TABLE SBREXT.FORM_COLLECTIONS (
  FORM_COLLECTION_IDSEQ CHAR(36) PRIMARY KEY,
  DESCRIPTION VARCHAR2(2000),
  NAME VARCHAR2(255) NOT NULL,
  XML_FILE_NAME VARCHAR2(255),
  XML_FILE_PATH VARCHAR2(255),
  DATE_CREATED DATE default sysdate,
  CREATED_BY VARCHAR2(30),
  NAME_REPEAT_NUM NUMBER
);


CREATE TABLE SBREXT.FORMS_IN_COLLECTION (
  FORM_COLLECTION_IDSEQ CHAR(36) NOT NULL,
  FORM_IDSEQ CHAR(36),
  PUBLIC_ID NUMBER, 
  VERSION NUMBER(4,2),
  LONG_NAME VARCHAR2(4000) NOT NULL,
  LOAD_TYPE CHAR(36)
  LOAD_STATUS NUMBER,
  LOAD_UNLOAD_DATE DATE default sysdate
);

alter table SBREXT.FORMS_IN_COLLECTION 
add foreign key (FORM_COLLECTION_IDSEQ) 
references SBREXT.FORM_COLLECTIONS(FORM_COLLECTION_IDSEQ);



insert into DESIGNATION_TYPES_LOV_VIEW (DETL_NAME) values ('Form Loader')
insert into sbrext.DEFINITION_TYPES_LOV_EXT (DEFL_NAME) values ('Form Loader')


rem ALTER TABLE FORM_COLLECTIONS MODIFY date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP

ALTER TABLE SBREXT.FORMS_IN_COLLECTION ADD LOAD_TYPE CHAR(36);

rem alter table SBREXT.FORMS_IN_COLLECTION add foreign key (FORM_COLLECTION_IDSEQ) references SBREXT .FORM_COLLECTIONS(COLLECTION_IDSEQ);

rem DROP TABLE SBREXT.FORM_COLLECTIONS
rem DROP TABLE SBREXTFORMS_IN_COLLECTION

rem 2013-10-24
ALTER TABLE SBREXT.FORMS_IN_COLLECTION ADD NAME_REPEAT_NUM NUMBER;

ALTER TABLE SBREXT.FORMS_IN_COLLECTION MODIFY FORM_IDSEQ CHAR(36);

